name: "CI" # Note that this name appears in the README's badge
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

        django-tox-env:
          - "django42"
          - "django50"
          - "django51"

        exclude:
          # We don't want every combination of the above, as some are not compatible

          - python-version: "3.8"
            django-tox-env: "django50"

          - python-version: "3.9"
            django-tox-env: "django50"

          - python-version: "3.8"
            django-tox-env: "django51"

          - python-version: "3.9"
            django-tox-env: "django51"

    name: Python ${{ matrix.python-version }} in use with ${{ matrix.django-tox-env }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64" # optional x64 (default) or x86.
      - name: Install test requirements
        run: pip install -r requirements_test.txt
      - name: Run tox
        run: tox -e py${{ matrix.python-version }}-${{ matrix.django-tox-env }}

  lint:
    runs-on: ubuntu-latest
    name: Flake 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install test requirements
        run: pip install -r requirements_test.txt
      - name: Run flake8 linting
        run: tox -e py3.12-flake8

  release:
    name: django-allow-cidr Release
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies for package building only
        run: pip install build
      - name: Build package for upload to PyPI
        run: python -m build .
      - name: Upload the distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.7
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
